### ISSUE TITLE
literal 标签不正常工作.

### ISSUE THREAD

**Issue by lixiaoyan** [ecomfe/smarty4js#2]
例子:

``` smarty
{%literal%}
{%%}
{%literal%}
```

``` javascript
var Smarty = require("smarty4js");
var s = new Smarty();
s.render("...");
```

```
Error: Parse error on line 2:
{%literal%}{%%}{%literal%}{%*sma
-------------^
Expecting 'L', 'COMMENTS', 'ID', 'function', '/', 'block', 'capture', 'literal', 'nocache', 'strip', 'foreach', 'for', 'foreachelse', 'section', 'sectionelse', 'while', 'STR', 'if', 'else', 'elseif', '-', '++', '--', '!', '(', '[', '$', 'G', 'NUM', 'true', 'false', 'null', got 'R'
    at Object.parseError (/home/intptr/Codes/tangscan-fe/node_modules/smarty4js/lib/parser/index.js:677:15)
    at Object.parse (/home/intptr/Codes/tangscan-fe/node_modules/smarty4js/lib/parser/index.js:742:22)
    at Object.exports.parse (/home/intptr/Codes/tangscan-fe/node_modules/smarty4js/lib/parser/index.js:1245:51)
    at Smarty.compile (/home/intptr/Codes/tangscan-fe/node_modules/smarty4js/index.js:81:23)
    at Smarty.render (/home/intptr/Codes/tangscan-fe/node_modules/smarty4js/index.js:101:17)
    ...
```

**Comment by zoumiaojiang** [comment]
你好，这个是我一开始就留的一个已知的坑，当时我认为大家都会默认的不使用 ｀{｀  ｀ }｀作为分界符（事实smarty4js的默认分界符是 `{%`   `%}` ）， 那么在模版中写js或者css的inline代码不会是什么问题。

我确实没有考虑到你这种应用场景（需要打印出 `{%`  `%}` ）。
这个问题我在修复中，已经push了一个简版的解决方案，但是这个方案还有有很大漏洞（我暂时不会发版），我会继续修复，但是继续修复需要改动的地方可能比较多。
